import { Reason } from './reason';

export const REASONS: Reason[] = [
  { id: 1, title: 'Waardestijging' },
  { id: 2, title: 'Bezwaar aanslag OZB gebruik' },
  { id: 3, title: 'Bsr-no-26-3 ' },
  { id: 4, title: 'Geen gebruiker van het pand' },
  { id: 5, title: 'Geen eigenaar van het pand' },
  { id: 6, title: 'Geen E of G van het volledige pand' },
  { id: 7, title: 'Geen zelfstandig gedeelte' },
  { id: 8, title: 'Geen sprake van woonruimte' },
  { id: 9, title: 'Geen sprake van bedrijfsruimte' },
  { id: 10, title: 'Geen sprake van samenstel' },
  { id: 11, title: 'Soort pand' },
  { id: 12, title: 'Geen pand op peildatum' },
  { id: 13, title: 'Waarde OZB te veel gestegen' },
  { id: 14, title: 'Waarde hoog vergelijkingsobjecten' },
  { id: 15, title: 'Te lage daling' },
  { id: 16, title: 'Vergelijking indexcijfers' },
  { id: 17, title: 'Stichtingskosten of aankoopprijs' },
  { id: 18, title: 'Waarde te hoog tov verkoopcijfers' },
  { id: 19, title: 'Vergelijkingspanden niet vergelijkbaar' },
  { id: 20, title: 'Betere vergelijkingsobjecten' },
  { id: 21, title: 'Waarde is te hoog' },
  { id: 22, title: 'Vergelijkingspanden niet identiek' },
  { id: 23, title: 'Ten onrechte huurw.kap.methode' },
  { id: 24, title: 'Huurwaardekapitalisatiefactor te hoog' },
];
